---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 1h
  ref:
    tag: v0.15.2
  url: https://github.com/metallb/metallb
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./config/native
  prune: true
  sourceRef:
    kind: GitRepository
    name: metallb
